using System;

public class InputCodeRC
{
    public static int cannonBack = 1;
    public static int cannonFire = 4;
    public static int cannonForward = 0;
    public static int cannonLeft = 2;
    public static int cannonMount = 5;
    public static int cannonRight = 3;
    public static int cannonSlow = 6;
    public static int chat = 6;
    public static int dash = 2;
    public static int horseBack = 1;
    public static int horseForward = 0;
    public static int horseJump = 5;
    public static int horseLeft = 2;
    public static int horseMount = 6;
    public static int horseRight = 3;
    public static int horseWalk = 4;
    public static int levelBack = 1;
    public static int levelCursor = 6;
    public static int levelDelete = 8;
    public static int levelDown = 5;
    public static int levelFast = 0x10;
    public static int levelForward = 0;
    public static int levelLeft = 2;
    public static int levelPlace = 7;
    public static int levelRBack = 11;
    public static int levelRCCW = 14;
    public static int levelRCW = 15;
    public static int levelRForward = 10;
    public static int levelRight = 3;
    public static int levelRLeft = 12;
    public static int levelRRight = 13;
    public static int levelSlow = 9;
    public static int levelUp = 4;
    public static int liveCam = 7;
    public static int mapMaximize = 4;
    public static int mapReset = 5;
    public static int mapToggle = 3;
    public static int reelin = 0;
    public static int reelout = 1;
    public static int titanAntiAE = 11;
    public static int titanBack = 1;
    public static int titanBite = 12;
    public static int titanCover = 13;
    public static int titanForward = 0;
    public static int titanGrabBack = 9;
    public static int titanGrabFront = 8;
    public static int titanGrabNape = 10;
    public static int titanJump = 5;
    public static int titanLeft = 2;
    public static int titanPunch = 6;
    public static int titanRight = 3;
    public static int titanSit = 14;
    public static int titanSlam = 7;
    public static int titanWalk = 4;
}

