name: Acquire activation file
on: 
  workflow_dispatch:
    inputs:
      unityVersion:
        description: 'Unity Version'     
        required: true
        default: 'warning'
jobs:
  activation:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest
    steps:
    # Request manual activation file
    - name: Request manual activation file
      id: getManualLicenseFile
      uses: game-ci/unity-request-activation-file@v2.0-alpha-1
      with:
        unityVersion: ${{ github.event.inputs.unityVersion }}
        
     # Upload artifact (Unity_v20XX.X.XXXX.alf)
    - name: Expose as artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.getManualLicenseFile.outputs.filePath }}
        path: ${{ steps.getManualLicenseFile.outputs.filePath }}
