name: Continious Integration

on:
  pull_request: {}
  push: { branches: [development] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE2 }}
  UNITY_VERSION: 2020.2.3f1

jobs:
  testRunnerInEditMode:
    if: false
    name: Test in editmode 📝
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-
      # Configure test runner
      - uses: game-ci/unity-test-runner@v2.0-alpha-2
        id: editTestRunner
        with:
          testMode: editmode
          unityVersion: ${{ env.UNITY_VERSION }}
          useNetworkHost: true
          customParameters: |
            -nographics
      # Upload artifact
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (edit mode)
          path: ${{ steps.editTestRunner.outputs.artifactsPath }}
          
  testRunnerInPlayMode:
    if: false
    name: Test in playmode 📺
    runs-on: ubuntu-latest
    steps:
      # Checkout repository (required to test local actions)
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-
      # Configure test runner
      - uses: game-ci/unity-test-runner@v2.0-alpha-2
        id: playTestRunner
        with:
          testMode: playmode
          unityVersion: ${{ env.UNITY_VERSION }}
          customParameters: |
            -nographics
            -silent-crashes
            -force-glcore
              
      # Upload artifact
      - uses: actions/upload-artifact@v1
        with:
          name: Test results (play mode)
          path: ${{ steps.playTestRunner.outputs.artifactsPath }}
          
  windowsWithSonarQube:
    name: Build for Windows64 with SonarQube
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
                                          
      # Build
      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows64
      
      # Experimental .csproj modifier. This modifies .csproj to be compatible with SonarQube analysis
      - name: File Content Replacer
        id: hello
        uses: Lithrun/file-content-replacer@main
        with:
          who-to-greet: 'Mona the Octocat'
      
       # This will automatically deploy the Builds
      - uses: actions/upload-artifact@v2
        with:
          name: Projects
          path: "*.csproj"
      
      - name: SonarQube analysis
        if: always()
        uses: AoTTG-2/unity-runner@master
        with:
          entrypoint: /sonar-scanner.sh
          projectKey: AoTTG-2_AoTTG-2
          projectName: AoTTG-2
          sonarOrganisation: aottg-2
          solution: AoTTG-2.sln
          beginArguments: /d:sonar.verbose="true"
        env:
          FrameworkPathOverride: /opt/Unity/Editor/Data/MonoBleedingEdge/
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
 
  buildOtherPlatforms:
    if: false
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
    steps:     
      # Checkout
      - uses: actions/checkout@v2
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
          restore-keys: |
            Library
          
      # Build
      - uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      # This will automatically deploy the Builds
      #- uses: actions/upload-artifact@v1
      #  with:
      #    name: Build
      #    path: build
